/** Declaration file generated by dts-gen */

export = merge;

declare function merge(clone: any, ...args: any[]): any;

declare namespace merge {
    const prototype: {
    };

    function clone(input: any): any;

    function recursive(clone: any, ...args: any[]): any;

    namespace clone {
        const prototype: {
        };

    }

    namespace recursive {
        const prototype: {
        };

    }

}

